#version 450

// workgroup size (must match vkCmdDispatch)
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

struct Vertex {
    vec3 position;
    float pad0;
    vec3 normal;
    float pad1;
    vec3 color;
    float pad2;
    vec2 uv;
    vec2 pad3;
};

layout(std430, binding = 0) buffer VertexBuffer {
    Vertex vertices[];
};

layout(push_constant) uniform PushConstants {
    ivec2 chunkOffset;
    float seed;
} push;


const float CELL_SIZE = 1.0;
const int CHUNK_VERTEX_COUNT = 64;

// simple hash and noise function
float hash(vec2 p)
{
    uvec2 q = uvec2(ivec2(floor(p)));
    uint s = floatBitsToUint(push.seed);
    
    q = q * uvec2(1597334677U, 3817628729U);
    uint n = (q.x ^ q.y ^ s) * 1597334677U;

    return float(n) * (2.0 / 4294967295.0) - 1.0;
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * (3.0 - 2.0 * f);
    
    return mix(mix(hash(i + vec2(0.0,0.0)), hash(i + vec2(1.0,0.0)), u.x),
               mix(hash(i + vec2(0.0,1.0)), hash(i + vec2(1.0,1.0)), u.x), u.y);
}

// FBM
float getHeight(float x, float z)
{
    vec2 pos = vec2(x, z) * 0.0025;

    float y = 0.0;
    float amplitude = 128.0;
    float frequency = 1.0;

    for(int i = 0; i < 6; i++)
    {
        y += noise(pos * frequency) * amplitude;

        frequency *= 2.0;
        amplitude *= 0.5;
    }

    return y;
}

void main() {
    uint x = gl_GlobalInvocationID.x;
    uint z = gl_GlobalInvocationID.y;

    if (x >= CHUNK_VERTEX_COUNT || z >= CHUNK_VERTEX_COUNT) return;

    uint index = z * CHUNK_VERTEX_COUNT + x;

    float localX = x * CELL_SIZE;
    float localZ = z * CELL_SIZE;

    float worldX = (float(push.chunkOffset.x) * float(CHUNK_VERTEX_COUNT - 1) * CELL_SIZE) + localX;
    float worldZ = (float(push.chunkOffset.y) * float(CHUNK_VERTEX_COUNT - 1) * CELL_SIZE) + localZ;

    float height = getHeight(worldX, worldZ);

    float left   = getHeight(worldX - CELL_SIZE, worldZ);
    float right  = getHeight(worldX + CELL_SIZE, worldZ);
    float down   = getHeight(worldX, worldZ - CELL_SIZE);
    float up     = getHeight(worldX, worldZ + CELL_SIZE);

    vec3 normal = normalize(vec3(left - right, 2.0 * CELL_SIZE, down - up));

    vec2 uv = vec2(worldX, worldZ) * 0.1;

    float steepness = 1.0 - normal.y;

    vec3 grass = vec3(0.15, 0.55, 0.15);
    vec3 rock  = vec3(0.45, 0.45, 0.45);
    vec3 snow  = vec3(1.0);

    vec3 color = grass;

    // Steep slopes become rocky
    color = mix(color, rock, smoothstep(0.25, 0.6, steepness));

    // High elevations become snowy
    color = mix(color, snow, smoothstep(50.0, 90.0, height));

    vertices[index].color = color;

    vertices[index].position = vec3(localX, height, localZ);
    vertices[index].normal = normal;
    vertices[index].uv = vec2(worldX, worldZ) * 0.1;
}