<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Library</OutputType>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Laika.Managed/Laika.Managed.csproj" />
	</ItemGroup>

</Project>